### ISSUE TITLE
Gather activity prompts in WTF GitHub org

### ISSUE THREAD

**Issue by karawoo** [rstudio-conf-2020/what-they-forgot#14]
I believe the links below are the repos for the existing activities. @jennybc when you have a chance, would you create the WTF GitHub organization so we can centralize the activities there?

Project-oriented workflows:
- https://github.com/jennybc/wtf-explore-libraries
- https://github.com/jennybc/wtf-packages-report

Debugging:
- https://github.com/jimhester/wtf-debugging
- https://github.com/jimhester/wtf-read-source

Personal R admin:
- https://github.com/jimhester/wtf-startup
- https://github.com/jimhester/wtf-source-package

**Comment by jennybc** [comment]
Organization created and you @karawoo and @jimhester have been invited. I can work on it a bit in the background Monday / Tuesday while I'm TAing a Tidy Tools workshop. I.e. I'll move repos over that should be under this organization.

**Comment by jimhester** [comment]
I moved my activity repos over.

**Comment by jennybc** [comment]
ALL DONE

Project-oriented workflows:
- https://github.com/rstats-wtf/wtf-explore-libraries
- https://github.com/rstats-wtf/wtf-packages-report
- https://github.com/rstats-wtf/wtf-packages-report-EXAMPLE

Debugging:
- https://github.com/rstats-wtf/wtf-debugging
- https://github.com/rstats-wtf/wtf-read-source

Personal R admin:
- https://github.com/rstats-wtf/wtf-startup
- https://github.com/rstats-wtf/wtf-source-package
