### ISSUE TITLE
Set up Community thread for setup questions

### ISSUE THREAD

**Issue by karawoo** [rstudio-conf-2020/what-they-forgot#2]
Start a thread for setup questions a la [last year's](https://community.rstudio.com/t/what-they-forgot-to-teach-you-system-setup-for-rstudio-conf-2019/20914) and add the link to pre-work section of README.md.

**Comment by jennybc** [comment]
When this happens, make a PR to Happy Git so the link appear there too. I've already updated the workshops page to reflect that rstudio::con 2020 will be the next offering:

https://happygitwithr.com/workshops.html#rstudioconf-2020
