### ISSUE TITLE
Update slides

### ISSUE THREAD

**Issue by karawoo** [rstudio-conf-2020/what-they-forgot#20]
I've put copies of all keynote files from 2019-rsc into the 2020-rsc google drive folder, plus added 2018-09_latinr-purrr.key as purrr.key. Besides any content changes, all slides need some minor adjustments (dates, names, using [branded title slide](https://drive.google.com/drive/folders/189bz9HHNKl0iqT7TgR2qft7socFgh9CV), some mention "most recent" R/RStudio versions that should be updated, etc.). I will update the following and check off when I've exported to PDF and moved them over into this repo.

- [x] project-oriented-workflow.key
- [x] git-and-github-early-usage.key
- [x] purrr.key
- [x] R-startup.key
- [x] wtf-closing.key
- [x] wtf-opening.key

@jimhester and @jennybc I think the following are slides for your sections, I don't want to interfere with them, but if you want me to take care of updating the title slides and such I'm happy to do so. 

- Debugging.key
- dev-environment.key
- git-and-github-daily-workflows.key
- install-source-package.key
- Read Source.key

**Comment by jennybc** [comment]
We got a DropBox link today for Keynote (and PowerPoint) templates (internal RStudio Slack). I think the only part of any official template we should feel obligated to use is a title slide at the start of each deck. I'm also not sure about the connection of the Keynote template at the Drive link above vs. today's DropBox link 🤔

My session on Git has 1 slide deck, now known as "git-and-github-daily-workflows.key". So you can delete or cross-out the bullet points for "git-branching.key" and "git-remotes.key".

Yes I will make sure this deck has an rstudio conf 2020 templated title slide.

**Comment by karawoo** [comment]
The template I linked was shared in the instructors call Carl ran last month, I imagine they are the same or similar? It's just the photo of San Francisco with the rstudio::conf logo/location/dates at the bottom and space in the middle for a title. Carl said on the call that it would be good if we used this as the title slide, but that the rest of the slides could be whatever.

**Comment by karawoo** [comment]
I've removed git-branching and git-remotes from the list above and also from the 2020-rsc drive folder.

**Comment by karawoo** [comment]
I've done most of the updates but am leaving this open until I can:
- Update the TA slides in the opening and closing keynotes (I emailed the TAs today for their affiliations and photos)
- Figure out where the new git/github https/ssh/PAT diagram should go in the git slides

**Comment by karawoo** [comment]
Reminder to self: also go back to all slides and add the new requirements sent out by Carl today
